### ISSUE TITLE
plugin updates don't append items.yml with new items

### ISSUE THREAD

**Issue by EmpathDemon** [ksafin/DynamicEconomy#101]
I have to generate a new items.yml and then manually diff the new items, and then add them again to my original file. Probably not a bug per se, but it makes updating a whole... process.

Love the new items. I noticed a couple typos I think:

Entry below JUNGLESLAB is "JUNGLESLABK" with reduced options

"GOLDNUGset"

"LEATHERPANTS", when other leg-slot items are named "...LEGGINGS"

Also the new birch/jungle/etc steps are still missing, along with jack-o-lanterns and... probably something else I've forgotten.

**Comment by ksafin** [comment]
Yeah. That's the current process right now (backing up Items.yml, deleting it, loading DE to generate new one).

Alas, the new update (v .8.53) had an Alias feature that should eliminate this problem because you can now add items to Items.yml, appropriate aliases to alias.yml, and it should work no problem in-game. For this reason, I don't think I'll ever need to update DE for new items.
