### ISSUE TITLE
Conflict with MineReset

### ISSUE THREAD

**Issue by Master-Zangetsu** [ksafin/DynamicEconomy#105]
Thought it best to start a new issue here now that it seems ive gotten to the root of the problem

when i add DynamicEconomy to the server with a MineReset (http://dev.bukkit.org/server-mods/minereset/) plugin installed

DE wont create a config and gives the error http://pastie.org/4066411

however when i remove the MineReset.jar everything works as it should.

i will of course be opening a simlar issue with them on there page ....

i hope this can be resolved

**Comment by ksafin** [comment]
I will investigate the issue, and I hope that the guys at MineReset will likewise look into it.

As of now, I guess for new versions of DE with new config.yml versions your best off disabling MineReset, turning on DE to generate config, then re-enabling MineReset.

**Comment by Master-Zangetsu** [comment]
will it work like this? i dont need to keep MineReset off to allow DE to work as usual?

**Comment by ksafin** [comment]
Well I'm just assuming from your issue that your only problem was that DE wouldn't generate the config.yml with MineReset on, but it did with MineReset off.

If that's the only issue, I'd expect DE to work fine with MineReset on, so long as it has access to config.yml, and it hooks into the economy via Vault.

If however, you DE errors in console with MineReset on, then turn MineReset off and see if it works fine.

Again, I don't know if you're having issues besides the config.yml generation, I just assumed your only problem was config.yml generation based on your post.

**Comment by Master-Zangetsu** [comment]
just tested it it doesnt work.

when i re-enable MineReset DynamicEconomy doesnt recognise any of the commands

it is however producing another error

http://pastie.org/4075936

**Comment by bitWolfy** [comment]
Hello there!

I am the developer of MineReset, and I have been looking into the issue. The problem seems to be in the AutoUpdater, and even though I am not sure why or how this happened, it looks like DE is trying to use the version of AU I am using.

Judging by the error log, the problem is on the DE side, but I will gladly modify my code for the sake of compatibility.
- bitWolfy

**Comment by ksafin** [comment]
Hello bitWolfy!

Thanks for the contact! I was going to look into the issue today but you're one step ahead of me! 

However, what's your take on this? I have a version of AU bundled with DE, I'm finding it odd that DE would try to access your version of AU. Error log seems to say that it can't find a constructor, which I take it is missing in your version?

Let me know, thanks!

**Comment by bitWolfy** [comment]
I have no idea why would it want to access my plugin at all! It is not supposed to do that at all. 
However, renaming the class file back to the original one did not fix the problem. It is producing a slightly different error: http://pastie.org/4083119

What I am intending to do now is to check if the problem is with either of our plugins or with AutoUpdater itself. I'll create a simple plugin that will do nothing but check for a version with AU. If it throws an error, then we know that it's AU.

I'll let you know what comes out of this.

**Comment by ksafin** [comment]
It is very odd. 

But, great, thank you!

**Comment by bitWolfy** [comment]
AU's not the case, a tester plugin resulted in no errors. More ideas?

**Comment by bitWolfy** [comment]
Scratch that, I made a mistake. It does result in an error. Here's the log: http://pastie.org/4084239

**Comment by bitWolfy** [comment]
Fixed the issue by renaming the AU package.
`couk.Adamki11s.AutoUpdater --> com.wolvencraft.AutoUpdater`
No more errors, though this entire situation is weird. Not sure why the updater is trying to access other plugins at all.
(I know that renaming other people's packages is a rude thing to do, but, well, that's an easy fix)

**Comment by ksafin** [comment]
Well, not much we can do about it.

It is a VERY unusual error and I'm still pretty perplexed by it.

Glad you got it fixed though.

**Comment by Master-Zangetsu** [comment]
brilliant thanks guys, nice to see plugin devs working together in this way to fix things. 

cant wait for the releases for this problem so i can get them both up and running on my server
