### ISSUE TITLE
Auto-update problem

### ISSUE THREAD

**Issue by mzx987** [ksafin/DynamicEconomy#13]
I'd like to thank you for adding the ability to turn off the auto-updater, but it still doesn't work for me.
I set enable-auto-updater to false and I still have the same problem.

I just want you to test two things:
1. Disable the internet connection you are on, disable the auto-updater, and run a server with the plugin and see what you get. (Because I am getting some kind of "cant read input/ouput url.")
2. Check the config to make sure it is not reseting the settings at all.

If I have to, I can post my logfile and show you what I mean.

**Comment by ksafin** [comment]
couldn't replicate the error, however I have gone to some lengths to try to make sure it shouldn't happen:

Changed the update-info html page to be on a dedicated webserver instead of my minecraft server.
Changed the file storage to be on dropbox instead of my server.

These two changes should prevent many more errors, since a majority of errors from Auto-Updater seem to be due to inability to connect to my server during downtime.
