### ISSUE TITLE
issues with permissions?

### ISSUE THREAD

**Issue by ghost** [ksafin/DynamicEconomy#15]
Hi there,

Thanks for working on this amazing plugin. I send a little donation awhile ago. I will send some more tomorrow to help out a little bit.

I think I have permissions issues with dynamic economy.

Some of the commands such as /getfloor or /hasupdate won't work when I have the dynamiceconomy.\* permission node set for some reason. I am using Vault obviously and bpermissions but they are updated so I am not sure the problem. I was testing on 1.2.3 with the latest craftbukkit dev build 2032.

Also, as a side note, when I did /sell cobble all it sold -1 cobble.

I love this plugin, it is amazing and will be even more amazing when its done the way you invision it. Thanks =)

**Comment by ksafin** [comment]
Thanks so much for all the support & donations Ryan! It helps a lot.

I'll look into it right now! Hopefully I can figure it out and let you know what's going on, or upload a fix if necessary.

**Comment by ksafin** [comment]
So, I just did some testing and couldn't find the problem.

I'm using the latest bPermissions, Vault, and DynamicEconomy, and I'm testing on 1.2.3 with build 2032.

I couldn't replicate any of the problems.

Do you think there could be other plugins conflicting with DE?

What happens if you try to disable all plugins besides your economy, vault, bperms, and DE?

Let me know, thanks.

**Comment by ghost** [comment]
Tested this and it seems to work fine with a default world name with only those plugins. Could be conflicts with other plugins indeed. I will test more and try to track down which one. Thanks =)

**Comment by ksafin** [comment]
Great, glad it works!

Let me know what plugin is causing the conflict if you find out, I might look into what's causing it.

**Comment by ghost** [comment]
Aha, it seems to be iConomy causing this. I want to switch to BOSE or CraftConomy but I am not sure all my plugins support them or not.

**Comment by ksafin** [comment]
Well hold on;

As far as I'm aware, there hasn't been an iConomy version for any Bukkit 1.2.3 version, the latest iConomy version only supports up to 1.1.

Am I wrong?

I was testing with BOSE lately because the latest iConomy hasn't been released for this bukkit verison yet.

I normally use iConomy to test and have not had these issues.

**Comment by ghost** [comment]
Oh, well that could be the reason then for sure. It says it works with 1.1-R7 but I am using it without any issues other than this. So maybe it is the problem with it. But that is alright with me. It is working fine now. Very much appreciated =)

**Comment by ksafin** [comment]
No problem!
Hope it keeps working :)

Thanks for the support :)
