### ISSUE TITLE
Not enough money to purchase. Balance: 27.012346845648496

### ISSUE THREAD

**Issue by Neodork** [ksafin/DynamicEconomy#59]
It returns with 15 decimals could you make sure it only returns with 2 ?

Oh and wouldn't want to make a new ticket for this but, I got my velocity on % BUT when I buy one item, and then sell it right away the price will decrease... I think you did the calculation wrong so I went to check it out.
Example:

At the moment my results are:
Price: 10$
Velocity 0.02 (2%)

When selling 10 this will happen:
10 \* (0.98^10) = 8.170728069 (New display price: 8.17)

When buying 10 right after this will happen:
8.170728069 \* (1.02^10) = 9.960071923 (New display price 9.96)

What's supposed to happen, when buying 10 is:
8.170728069 / (0.98^10) = 10

Thanks in advance

**Comment by ksafin** [comment]
Balance rounding fixed, rounded to two decimal places.

The DE calculation for percent-velocities was very different than this, and the reason it made the price slightly less than the original was, is because since the price was lower the percent change was slightly lower.

Regardless, your solution is very elegant, and I put it in. Thank you for this!
