### ISSUE TITLE
GOLDENAPPLE OVERPRICED

### ISSUE THREAD

**Issue by confuz3d** [ksafin/DynamicEconomy#60]
Costs about 250$ to craft and you can sell it for 25000 by default. You should fix the default ceiling and floor to somehting lower.

**Comment by Spiritwo** [comment]
you can always change it yourself in the Items.yml file

**Comment by confuz3d** [comment]
O rly? Lol.. I know but seriously it can be a f***ing pain if an admin didn't realize that and people starts abusing it. Fixing the default values would be a better fix, because anyways, who would pay 25000 for a golden apple?

**Comment by Neodork** [comment]
These values are default for a reason, they indicate nothing. Before you release any item using DE you should make sure it's stock,velocity,ceiling,floor are the desired amounts.

**Comment by ksafin** [comment]
Exactly what Spiritwo and Neodork indicated.
I set all the default prices, stocks, velocities, etc, as it fit into my server.

I set the apple and goldenapple before apples were readily available due to an MC update, so I made them both very expensive.
Similarly, since golden apples took 8 goldingots, I took the price of 8 goldingots, and tacked that onto the price of an apple to get the golden apple price.

This was before golden nuggets were released and used to make a golden apple.
